FORMAT: 1A
HOST: http://webgis.nature.cz/aopkrest/Evl/

# AOPK ČR - EVL

Rozhraní pro získávání informací o **Evropsky významných lokalitách soustavy Natura 2000 (EVL)**.

## EVL - karta dle ID [/{kod}?f={f}]

+ Parameters
    + kod: 2612 (number) - Kod EVL
    + f (string, optional) - formát výstupu
        + Default: html
        + Members
            + json
            + html
            + xml

### Přehled dotazů [GET]

+ Response 200 (application/json)
    + Attributes (LokalitaEVL)

## EVL - filtrování dle názvu [/filter/{pattern}?f={f}]

+ Parameters
    + pattern: Čes (string, optional) - řetězec pro vyhledání
    + f (string, optional) - formát výstupu
        + Default: html
        + Members
            + json
            + html
            + xml

            
### Přehled dotazů [GET]

+ Response 200 (application/json)
   + Attributes
        + lokality(LokalitaEVL)
        + lokality(LokalitaEVL)
        + lokality(LokalitaEVL)

## EVL - Zákres [/{kod}/shape?shapeFormat={shapeFormat}&crs={crs}&f={f}]
+ Parameters
    + kod: 2612 (number) - Kod EVL
    + shapeFormat (string, optional) - typ geometrie
        + Default: stgeometry
        + Members
            + stgeometry
            + kml
    + crs (string, optional) - typ souřadnicového systému. p.z.
    **Pokud je požadován výstupní formát KML a neuvede se parametr crs, použije se WGS84**.
        + Default: sjtsk
        + Members
            + sjtsk
            + jtsk
            + wgs84
    + f (string, optional) - formát výstupu
        + Default: html
        + Members
            + json
            + html
            + xml
    

### Přehled dotazů [GET]

+ Response 200 (application/json)
    + Attributes (ZakresEVL)
    
## EVL - Mapka [/{kod}/map?width={width}&height={height}&showsingle={showsingle}&bgmap={bgmap}&f={f}]
+ Parameters
    + kod: 2612 (number) - Kod EVL
    + width: 800 (number, optional) - výška mapky
    + height: 500 (number, optional) - šířka mapky
    + showsingle: false (boolean, optional) - zobrazení zákresů všech lokalit/ pouze vybrané lokality
    + bgmap (string, optional) - typ podkladové mapy
        + Default: zm
        + Members
            + ortofoto
            + zm
    + f (string, optional) - formát výstupu
        + Default: html
        + Members
            + json
            + html
            + xml
    

### Přehled dotazů [GET]

+ Response 200 (application/json)
    + Attributes (ZakresEVL)

# Data structures

## LokalitaEVL
+ Kod: 2502 (number) - kód lokality v ústředním seznamu ochrany přírody
+ Sitecode: CZ0110142 (string) - sitecode lokality
+ Nazev: Blatov a Xaverovský háj (string) - název lokality
+ Rozloha: 213.885 (number) - rozloha (ha)
+ Es: ano (enum[string]) - Je na evropském seznamu?
    + Members
    + ano
    + ne
+ Bioregion: c (enum[string]) - biogeografické oblasti ve kterých leží lokalita
    + Members
    + p - panonská
    + c - kontinentální 
    + pc - panonská i kontinentální
+ NChu: `PR-část, PP část` (string) - `překryvy lokality s ostatními chráněnými územými (MZCHÚ), oddělené čárkamy (území NPP,NPR,PR,PP,CHKO v kombinaci část - pouze částečný překryv)`

## ZakresEVL
+ Kod: 2612 (number) - kód lokality v ústředním seznamu ochrany přírody
+ Shapes: `polygon ((-829460 -1018247, -829460 -1010403, -816512 -1010403, -816512 -1018247, -829460 -1018247))` (array[string]) - vrací souřadnice zákresu ve formátu ST_GEOMETRY